---
name: Bazel files linter
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  bazel-formatting-check:
    name: Run buildifier check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run buildifier
        uses: jbajic/buildifier@v1
        with:
          buildifier-version: 7.3.1
          mode: fix
